development:
  client_id: '1078653378998-2g6n8i60asmdoun67umd13na6fbs7s16.apps.googleusercontent.com'
  client_secret: 'Q5BqtJ18U9sj1VWOqBCqCr7F'

local:
  client_id: '1078653378998-2g6n8i60asmdoun67umd13na6fbs7s16.apps.googleusercontent.com'
  client_secret: 'Q5BqtJ18U9sj1VWOqBCqCr7F'

staging:
  client_id: '1078653378998-2g6n8i60asmdoun67umd13na6fbs7s16.apps.googleusercontent.com'
  client_secret: 'Q5BqtJ18U9sj1VWOqBCqCr7F'

production:
  client_id: '1078653378998-2g6n8i60asmdoun67umd13na6fbs7s16.apps.googleusercontent.com'
  client_secret: 'Q5BqtJ18U9sj1VWOqBCqCr7F'
